version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/rails/Dockerfile
      args:
        RUBY_VERSION: '2.6.3'
        RAILS_VERSION: '5.2.0'      
        WORKDIR: '/app'
    image: sherllo/rails_engine:5.2.0
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/app/bundle
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vim

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

  # FOR DEBUG
  # docker-compose run --service-ports debug
  debug:
    <<: *backend
    command: /bin/bash
    ports:
      - '3000:3000'
      - '3002:3002'
    depends_on:
      - redis
      - mysql

volumes:
  mysql-db:
  redis:
  bundle: